# 100 numpy exercises



#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np
import pandas as pd
import random as rd
from sklearn import preprocessing as prp

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
print(np.__version__)

1.26.4


#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [15]:
print(x.nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [17]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [48]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
r=np.random.randint(10,49,10)
r

array([13, 34, 30, 27, 11, 21, 20, 39, 25, 28])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [21]:
print(np.sort(r))
r

[11 13 20 21 25 27 28 30 34 39]


array([13, 34, 30, 27, 11, 21, 20, 39, 25, 28])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [52]:
xx=np.random.randint(0,8,[3,3])
xx

array([[0, 2, 6],
       [5, 4, 1],
       [2, 5, 5]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
def non_z_el(listt):
    for i in range(len(listt)):
        if listt[i]>0:
           print(i)
print(non_z_el([1,2,0,0,4,0])) 


0
1
4
None


#### 11. Create a 3x3 identity matrix (★☆☆)

In [68]:
id=np.eye(3,3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [78]:
tens=np.random.randint(4,size=(3, 3,3))
tens

array([[[0, 2, 1],
        [2, 2, 1],
        [0, 0, 3]],

       [[3, 0, 2],
        [2, 3, 3],
        [1, 1, 3]],

       [[0, 3, 0],
        [1, 1, 0],
        [0, 0, 1]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
ar1=np.random.randint(10, size=(10,10))
print(ar1)
mmin=np.min(ar1)
mmax=np.max(ar1)
print('Min =',mmin, 'Max =',mmax)

[[1 3 8 5 8 7 3 7 9 5]
 [9 2 0 8 1 0 5 5 2 2]
 [7 0 3 4 5 0 6 2 6 7]
 [3 6 6 4 7 7 7 0 6 0]
 [3 4 2 5 2 3 5 5 2 2]
 [1 5 9 7 1 3 7 6 7 3]
 [6 7 7 3 1 8 3 8 0 1]
 [4 2 3 4 3 4 1 5 3 1]
 [7 3 6 7 1 6 1 4 0 2]
 [0 8 5 3 8 8 4 0 6 2]]
Min = 0 Max = 9


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
vec=np.random.randint(0,9,30)
print(np.mean(vec),np.var(vec),np.std(vec))


3.2 5.893333333333333 2.4276188608044165


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [46]:
x=np.random.randint(3,9)
y=np.random.randint(3,9)
x,y
z=np.zeros([x,y])
z[0,:]=1
z[-1,:]=1
z[:,-1]=1
z[:,0]=1
z

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [13]:
ar=np.random.randint(0,9,[3,3])
bar=np.pad(ar,pad_width=1,constant_values=0)
bar

array([[0, 0, 0, 0, 0],
       [0, 7, 1, 0, 0],
       [0, 5, 8, 4, 0],
       [0, 5, 7, 6, 0],
       [0, 0, 0, 0, 0]])

nan

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [92]:
z=np.random.randint(0,10,[5,5])
for i in range(1,5):
    z[i,0:i]=np.random.randint(1,5)
z

array([[0, 2, 1, 9, 5],
       [1, 8, 1, 2, 8],
       [1, 1, 9, 1, 9],
       [3, 3, 3, 7, 6],
       [4, 4, 4, 4, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [100]:
checker=np.ones([8,8])
checker[::2,::2]=0
checker

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [116]:
s=0
for i in range(6):
    for j in range(7):
        for k in range(8):
            s+=1
            if s==100 :
                print(i,j,k)
#OR
shape=(6,7,8)
ind=np.unravel_index(99,shape)
ind

1 5 3


(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [128]:
ar1=np.array([1,0,1,0])
ar2=np.tile(ar1,(8,2))
ar2

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [146]:
x = np.random.randint(0, 9, [5,5])
y=prp.normalize(x)
y

array([[0.34948162, 0.34948162, 0.43685203, 0.61159284, 0.43685203],
       [0.07495317, 0.59962535, 0.        , 0.59962535, 0.52467218],
       [0.49487166, 0.49487166, 0.57735027, 0.08247861, 0.41239305],
       [0.29002095, 0.48336824, 0.77338919, 0.29002095, 0.        ],
       [0.49029034, 0.68640647, 0.19611614, 0.49029034, 0.09805807]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [188]:
#x=np.random.randint(0,9,[5,3])
#y=np.random.randint(0,9,[3,2])
z=np.ndarray([5,2])
#print ('x=  ',x)
#print('y= ',y)
for i in range(5):
    z[i,0]=
    z[i,1]=
        #x[i,0]*y[0,i]+x[i,1]*y[1,i]+x[i,2]*y[2,i]
    print (z[i,j])

9.0
9.0
9.0
9.0
9.0


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [11]:
x=np.random.randint(0,9,[10,])
x
for i in range(10):
    if (x[i]>3) and (x[i]<8):
        x[i]=-1*x[i]
print(x)

[ 0  2  0  0  1 -7  2  2  8 -4]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [41]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
# The first calculates the sum starting from -1: -1+0+1+2+3+4
# The second with numpy, calclates 0+1+2+3+4 ignoring the axis -1 that does not exist in an array of 1D

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#  Z**Z give the power Z of Z

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [45]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1728\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1728\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_1728\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [25]:
y=np.random.randint(0,9,[10,])
z=np.random.randint(0,9,[10,])  
dict={}
print(y)
print(z)
for i in range(10):
    j=0
    for j in range(10):
        if (z[j]==y[i])and(z[j] not in dict):
            print (f"La valeur {z[j]} est commune")
            dict.append(z[j])
        
        

[5 4 0 6 0 6 1 4 2 7]
[3 0 5 7 2 5 7 3 7 4]
La valeur 5 est commune


AttributeError: 'dict' object has no attribute 'append'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
from datetime import datetime as dt, timedelta as dlt

today = dt.today()
yesterday=today-dlt(days=1)
tomorrow=today+dlt(days=1)
print('Today is ',today.strftime('%y-%m-%d'))
print('Yesterday was ',yesterday.strftime('%y-%m-%d'))
print('Tomorrow will be ',tomorrow.strftime('%y-%m-%d'))
# Get yesterday's date
#yesterday = today - timedelta(days=1)

# Get tomorrow's date
#tomorrow = today + timedelta(days=1)

# Print the dates in a readable format
#print("Yesterday:", yesterday.strftime('%Y-%m-%d'))
#print("Today:", today.strftime('%Y-%m-%d'))
#print("Tomorrow:", tomorrow.strftime('%Y-%m-%d'))


Today is  24-10-12
Yesterday was  24-10-11
Tomorrow will be  24-10-13


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [51]:
x=np.random.randint(0,9,10)
print(x)
y=np.sort(x)
print(y)

[8 6 4 6 6 8 5 3 0 6]
[0 3 4 5 6 6 6 6 8 8]


#### 41. How to sum a small array faster than np.sum? (★★☆)

A is equal to B


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [111]:
A=np.random.randint(0,9,10)
B=np.random.randint(0,9,10)
cpt=0
for i in range(len(A)):
    if A[i]==B[i]:
        cpt+=1
if cpt==len(A):
    print ( 'A is equal to B')
else:
    print ( 'A and B are different')
print(A,B)

A and B are different
[4 2 7 6 5 2 2 6 3 0] [7 8 8 3 8 8 6 4 4 3]


#### 43. Make an array immutable (read-only) (★★☆)

In [121]:
C=np.random.randint(0,9,10)
C.flags.writeable=False
print(C)

[8 3 1 3 4 0 7 1 3 8]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [13]:
x=np.random.randint(10)
x

9

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)